"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var a = 1 - 5;
exports.default = a;
var firstname = 'abdul';
var lastname = 'sami';
var fullname = firstname + ' ' + lastname;
console.log(fullname);
var castname = 'meo';
var zaatnaam = 'rajput';
var dononaam = "".concat(castname, " ").concat(zaatnaam);
console.log(dononaam);
