var faviourtecolor = "blue";
console.log(faviourtecolor);
faviourtecolor = 'green';
console.log(faviourtecolor);
var username = "Abdul Sami";
console.log(username);
username = 'Rajput';
console.log(username);
//let firstname: string ='sindh';
//let lastname: string ='karachi';
//let fullname: string = firstname + ' ' + lastname;
//console.log(fullname);
var firstname = 'Abdul';
var lastname = 'Rafay';
var fullname = firstname + '' + lastname;
console.log(fullname);
var personname = 'meo';
var castename = 'rajput';
var completename = "".concat(personname, " ").concat(castename);
console.log(completename);
